# menu.py
menu = {
    "item_01": {"name": "【義美】小泡芙-巧克力171g", "category": "snack", "price": 88, "promotion": None},
    "item_02": {"name": "【多力多滋】美式辣起士(108g)", "category": "snack", "price": 36, "promotion": None},
    "item_03": {"name": "【蝦味先】原味超派包115g", "category": "snack", "price": 35, "promotion": None},
    "item_04": {"name": "【77】新貴派-花生(16g*18入)", "category": "snack", "price": 85, "promotion": None},
    "item_05": {"name": "【可樂果】原味(188g)", "category": "snack", "price": 52, "promotion": None},
    "item_06": {"name": "【Glico 格力高】Pocky百奇 巧克力餅乾棒(95g)", "category": "snack", "price": 99, "promotion": None},
    "item_07": {"name": "【LAY’S 樂事】原味洋芋片經濟包(166g)", "category": "snack", "price": 63, "promotion": "second_item_80_off"},
    "item_08": {"name": "【奧利奧】雙倍夾心餅乾-檸檬起司蛋糕口味(393g)", "category": "snack", "price": 89, "promotion": None},
    "item_09": {"name": "【卡迪那】德州薯條茄汁口味(90g)", "category": "snack", "price": 36, "promotion": None},
    "item_10": {"name": "【咔辣姆久】歡樂分享包-勁辣唐辛子95g", "category": "snack", "price": 44, "promotion": None},
    "item_11": {"name": "【天天果園】美國北極熊富士蘋果(8入禮盒_220g/顆)", "category": "fruit", "price": 535, "promotion": None},
    "item_12": {"name": "【天天果園】韓國空運無籽麝香綠葡萄(2盒_500-600g/盒)", "category": "fruit", "price": 355, "promotion": None},
    "item_13": {"name": "【天天果園】空運進口新鮮藍莓(3盒_125g/盒)", "category": "fruit", "price": 471, "promotion": None},
    "item_14": {"name": "【天天果園】台灣卡蜜拉紅肉哈密瓜(2顆禮盒/約4.5斤)", "category": "fruit", "price": 912, "promotion": None},
    "item_15": {"name": "【海陸管家】冷凍草莓_家庭號(1包_1kg/包)", "category": "fruit", "price": 640, "promotion": None},
    "item_16": {"name": "【老協珍】經典烏參佛跳牆 1630g(固形物630g)/盒", "category": "dishes", "price": 599, "promotion": "time_limited_90_off"},
    "item_17": {"name": "【呷七碗】櫻花蝦米糕 700g/盒", "category": "dishes", "price": 359, "promotion": None},
    "item_18": {"name": "【台南晶英】紅燒海鮮羹 1370g/盒", "category": "dishes", "price": 469, "promotion": None},
    "item_19": {"name": "【老協珍】冰糖豬腳 820g(固形物620g)/盒", "category": "dishes", "price": 359, "promotion": None},
    "item_20": {"name": "【郭老師】黃耆紅棗枸杞烏骨雞湯 2200g/包", "category": "dishes", "price": 399, "promotion": None},
    "item_21": {"name": "【小川漁屋】野生北海大干貝2包(500g±10%/包/10~13顆)", "category": "meat", "price": 1479, "promotion": None},
    "item_22": {"name": "【約克街肉鋪】天然放牧無毒黑羽土雞切塊2包(1000g±10%/包)", "category": "meat", "price": 1203, "promotion": None},
    "item_23": {"name": "【海陸管家】超大包美國單骨牛小排(1包_500g/包)", "category": "meat", "price": 499, "promotion": None},
    "item_24": {"name": "【海陸管家】嚴選鮮凍大草蝦(6盒_10-12尾/盒)", "category": "meat", "price": 1053, "promotion": None},
    "item_25": {"name": "【海陸管家】嚴選智利鮭魚切片(共12片_3片/約300g/包)", "category": "meat", "price": 699, "promotion": "buy1_get1_free"},
    "item_26": {"name": "【愛之味】健康的油切分解茶(無糖) (600gx6入)x4組", "category": "drink", "price": 388, "promotion": None},
    "item_27": {"name": "【每朝健康】綠茶650mlx24瓶", "category": "drink", "price": 439, "promotion": "second_item_80_off"},
    "item_28": {"name": "【Coca Cola 可口可樂】易開罐(330ml*6罐)", "category": "drink", "price": 79, "promotion": None},
    "item_29": {"name": "【立頓】奶茶(250ml*6入)", "category": "drink", "price": 40, "promotion": None},
    "item_30": {"name": "【Coca Cola 可口可樂】寶特瓶(2000ml)", "category": "drink", "price": 39, "promotion": None}
}
